# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: chore
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
